Add Category model
Stelmaschyk/book-store pull request #13
Opened 2024-10-28 14:10 UTC by Stelmaschyk

2024-10-28 14:38 UTC, Elena-Bruyako requested changes
see comments

2024-10-28 14:38 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/config/SecurityConfig.java
> +                        "/api/books/{id}",
let's refactor
```suggestion
                       .requestMatchers(
                                        antMatcher("/auth/**"),
                                        antMatcher("/swagger-ui/**"),
                                        antMatcher("/v3/api-docs/**"))
                                .permitAll()
```

2024-10-28 14:38 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/controller/CategoryController.java
> +@RequestMapping("/api/categories")
add s`erver.servlet.context-path=/api` to application.properties

```suggestion
@RequestMapping("/categories")
```

2024-10-28 14:38 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/controller/CategoryController.java
> +
remove empty line after class declaration
```suggestion
```

2024-10-28 14:38 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/controller/CategoryController.java
> +    public List<CategoryResponseDto> getAllCategories(Pageable pageable) {
it's better to return Page
```suggestion
    public Page<CategoryResponseDto> getAllCategories(Pageable pageable) {
```

2024-10-28 14:38 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/dto/book/CreateBookRequestDto.java
> +    private Set<Long> categoryIds;
```suggestion
    @NotEmpty
    private Set<Long> categoryIds;
```

2024-10-28 14:38 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/dto/book/UpdateBookRequestDto.java
> +    private Set<Long> categoryIds;
same here

2024-10-28 14:38 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/Book.java
> +    @ManyToMany(fetch = FetchType.LAZY)
```suggestion
    @ManyToMany
```

2024-10-28 14:38 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/Category.java
> +    private Set<Book> books = new HashSet<Book>();
```suggestion
```

2024-10-28 14:38 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/Category.java
> +    @Column(nullable = false)
```suggestion
    @Column(nullable = false, unique = true)
```

2024-10-28 14:38 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/service/CategoryService.java
> +@Service
```suggestion
```

2024-10-28 14:38 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/service/CategoryServiceImpl.java
> +    public CategoryResponseDto updateCategoryById(Long id, UpdateCategoryRequestDto updateDto) {
```suggestion
    @Override
    public CategoryResponseDto updateCategoryById(Long id, UpdateCategoryRequestDto updateDto) {
```

2024-10-28 14:38 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/08-create-categories-table.yaml
> +                    nullable: false
add unique

2024-11-02 18:25 UTC, Elena-Bruyako requested changes
see comments

2024-11-02 18:25 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/User.java
> +    @ManyToMany(fetch = FetchType.EAGER)
don't use Eager 
```suggestion
    @ManyToMany
```

2024-11-02 18:25 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/User.java
>      @JoinTable(name = "user_roles",
```suggestion
    @JoinTable(name = "users_roles",
```

2024-11-02 18:25 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/security/JwtAuthenticationFilter.java
>              return bearerToken.substring(PREFIX);
```suggestion
            return bearerToken.substring(TOKEN_STARTS_WITH.length());
```

2024-11-02 18:25 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/security/JwtAuthenticationFilter.java
>      private static final Integer PREFIX = 7;
remove

2024-11-02 18:25 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/security/JwtAuthenticationFilter.java
>      private static final String TOKEN_STARTS_WITH = "Bearer ";
```suggestion
    private static final String TOKEN_HEADER = "Bearer ";
```

2024-11-02 18:25 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/service/UserServiceImpl.java
>      @Override
```suggestion
    @Override
    @Transactional
```

2024-11-02 18:25 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/service/UserServiceImpl.java
> +        user.setRoles(Set.of(userRole));
Have you done Shopping Cart HW ? 
It's better to create shop cart when user registers. Add method to ShopCartService and use it here

2024-11-04 11:43 UTC, Stelmaschyk commented on src/main/java/mate/academy/bookstore/service/UserServiceImpl.java
> +        user.setRoles(Set.of(userRole));
Yes, I know, I added it for only set role in table "users-roles" to test conrollers with admin role. Ok, I deleted it and implemet in next task.

2024-11-04 12:21 UTC, Elena-Bruyako requested changes
see comments

2024-11-04 12:21 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/config/SecurityConfig.java
>                      .requestMatchers(
that are all what you need actually 
```suggestion
                    .requestMatchers(
                                        antMatcher("/auth/**"),
                                        antMatcher("/swagger-ui/**"),
                                        antMatcher("/v3/api-docs/**"))
                                .permitAll()
```

2024-11-04 12:21 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/Book.java
> +    @ManyToMany(fetch = FetchType.LAZY)
Could you please remove default fetch type? 

```suggestion
    @ManyToMany
```

2024-11-04 12:21 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/User.java
> +    @ManyToMany //(fetch = FetchType.EAGER)
```suggestion
    @ManyToMany
```

2024-11-04 12:21 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/service/UserServiceImpl.java
>      @Override
I wrote [this](https://github.com/Stelmaschyk/book-store/pull/13#discussion_r1826642347) comment about shopping cart (I checked that this is a next HW) so you can ignore my comment

Setting role to user should be done in previous HWs, so please add set role

2024-11-04 12:21 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/11-insert-categories-in-table.yaml
> +      id: insert-categories
redundant changeset

2024-11-04 12:21 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/12-insert-book-categories.yaml
> +      id: insert-books-categories
redundant changeset

2024-11-04 12:21 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/09-insert-books-in-table.yaml
> +      id: insert-book
redundant changeset

2024-11-04 13:40 UTC, Stelmaschyk commented on src/main/java/mate/academy/bookstore/model/Book.java
> +    @ManyToMany(fetch = FetchType.LAZY)
Logically))

2024-11-04 13:58 UTC, Elena-Bruyako approved these changes

2024-11-04 14:02 UTC, merged