Complete shopping cart task
Stelmaschyk/book-store pull request #14
Opened 2024-11-16 12:59 UTC by Stelmaschyk

2024-11-17 17:25 UTC, Elena-Bruyako requested changes
see comments

2024-11-17 17:25 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/controller/ShoppingCartController.java
> +    public CartItemResponseDto addBookToCart(@RequestBody @Valid CartItemRequestDto request,
```suggestion
    public ShoppingCartResponseDto addBookToCart(@RequestBody @Valid CartItemRequestDto request,
```

2024-11-17 17:25 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/controller/ShoppingCartController.java
> +    public CartItemResponseDto updateCartItem(@RequestBody @Valid CartItemUpdateDto request,
```suggestion
    public ShoppingCartResponseDto updateCartItem(@RequestBody @Valid CartItemUpdateDto request,
```

2024-11-17 17:25 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/mapper/ShoppingCartMapper.java
> +
remove empty line

2024-11-17 17:25 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/CartItem.java
> +@RequiredArgsConstructor
```suggestion
```

2024-11-17 17:25 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/CartItem.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
```

2024-11-17 17:25 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/CartItem.java
> +    @JoinColumn(name = "shopping_cart_id",nullable = false)
```suggestion
    @JoinColumn(name = "shopping_cart_id", nullable = false)
```

2024-11-17 17:25 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/CartItem.java
> +    @OneToOne
```suggestion
    @OneToOne(fetch = FetchType.LAZY, optional = false)
```

2024-11-17 17:25 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/CartItem.java
> +    @JoinColumn(name = "book_id",nullable = false)
```suggestion
    @JoinColumn(name = "book_id", nullable = false)
```

2024-11-17 17:25 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/ShoppingCart.java
> +@RequiredArgsConstructor
```suggestion
```

2024-11-17 17:25 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/ShoppingCart.java
> +    @OneToOne
You can use `@MapsId` here

2024-11-17 17:25 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/ShoppingCart.java
> +    @OneToMany(mappedBy = "shoppingCart")
```suggestion
    @OneToMany(mappedBy = "shoppingCart", cascade = CascadeType.ALL, orphanRemoval = true)
```

2024-11-17 17:25 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/ShoppingCart.java
> +    private Set<CartItem> cartItems;
```suggestion
    private Set<CartItem> cartItems = new HashSet<>();
```

2024-11-17 17:25 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/service/ShoppingCartServiceImpl.java
> +    public CartItemResponseDto addCartItem(User user, CartItemRequestDto request) {
```suggestion
    public ShoppingCartResponseDto addCartItem(User user, CartItemRequestDto request) {
```

2024-11-17 17:25 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/service/ShoppingCartServiceImpl.java
> +    public CartItemResponseDto updateBooksQuantity(User user, Long cartItemId,
```suggestion
    public ShoppingCartResponseDto updateBooksQuantity(User user, Long cartItemId,
```

2024-11-17 17:25 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/service/ShoppingCartServiceImpl.java
> +    }
Think where `@Transactional` should be

2024-11-17 19:26 UTC, Stelmaschyk commented on src/main/java/mate/academy/bookstore/model/CartItem.java
> +    @ManyToOne
Thanks for new knowledge! Its about "optional = false"

2024-11-17 19:26 UTC, Stelmaschyk commented on src/main/java/mate/academy/bookstore/model/ShoppingCart.java
> +    @OneToMany(mappedBy = "shoppingCart")
Thanks for new knowledge! Its about "orphanRemoval = true"

2024-11-22 07:42 UTC, liliia-ponomarenko approved these changes
good job! 👍

2024-11-22 07:42 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/10-create-shopping_carts-table.yaml
> +            referencedColumnNames: id
add one empty line at the end of the file ;) 
check other files

2024-11-26 18:59 UTC, merged