has implemented Order and OrderItem functionality
Stelmaschyk/book-store pull request #15
Opened 2024-11-26 19:21 UTC by Stelmaschyk

2024-11-27 07:52 UTC, liliia-ponomarenko requested changes
Good job! Let’s improve your solution;)

2024-11-27 07:52 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/bookstore/controller/OrderController.java
> +    @PostMapping
ResponseStatus.CREATED

2024-11-27 07:52 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/bookstore/controller/OrderController.java
> +                                        Pageable pageable,
Why do you need a Pageable parameter here?

2024-11-27 07:52 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/bookstore/controller/OrderController.java
> +    @ApiResponse(responseCode = "202",
So OK or ACCEPTED?

2024-11-27 07:52 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/bookstore/dto/order/OrderStatusRequestDto.java
> +    private Order.OrderStatus orderStatus;
NotNull

2024-11-27 07:52 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/bookstore/model/OrderItem.java
> +    @ManyToOne()
```suggestion
    @ManyToOne(fetch = FetchType.LAZY) 
```

2024-11-27 07:52 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/bookstore/model/OrderItem.java
> +    @ManyToOne
the same

2024-11-27 07:52 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/bookstore/repository/shoppingcart/ShoppingCartRepository.java
> +    Optional<ShoppingCart> findByUserId(@Param("id") Long id);
```suggestion
    Optional<ShoppingCart> findByUserId(Long id);
```

2024-11-27 07:52 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/bookstore/service/OrderServiceImpl.java
> +            return new OrderResponseDto();
Let’s  throw  custom exception

2024-11-27 07:52 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/bookstore/service/OrderServiceImpl.java
> +        order.setOrderItems(createSetOfOrderItems(order, cartItems));
should you clear the shopping cart?  Also, remember about Transactional

2024-11-27 07:52 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/bookstore/service/OrderServiceImpl.java
> +            .filter(orderItem -> orderItem.getId().equals(orderItemId))
Let’s  use `orderId` and `orderItemId` in the DB query to avoid this filtration

2024-11-27 07:52 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +
```suggestion
```
Only one empty line

2024-11-27 15:22 UTC, Elena-Bruyako requested changes
see comments

2024-11-27 15:22 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/controller/OrderController.java
> +                                  @RequestBody OrderStatusRequestDto requestDto) {
```suggestion
                                  @RequestBody @Valid OrderStatusRequestDto requestDto) {
```

2024-11-27 15:22 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/controller/OrderController.java
> +    public List<OrderResponseDto> getOrders(Authentication authentication) {
If you use one approach be consistent 
`@AuthenticationPrincipal User user`

2024-11-27 15:22 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/Order.java
> +    private OrderStatus orderStatus;
you can initialise status here and remove initialising from service method
```suggestion
    private OrderStatus orderStatus = OrderStatus.PENDING;
```

2024-11-27 15:22 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/Order.java
> +    private LocalDateTime orderDate;
you can initialise date here and remove initialising from service method
```suggestion
    private LocalDateTime orderDate = LocalDateTime.now();
```

2024-11-27 15:22 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/OrderItem.java
> +@Table(name = "orders_items")
```suggestion
@Table(name = "order_items")
```

2024-11-27 15:22 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/service/OrderItemServiceImpl.java
> +public class OrderItemServiceImpl implements OrderItemService {
all logic should be in OrderServiceImpl, remove this service

2024-11-27 15:22 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/service/OrderServiceImpl.java
> +            throw new EntityNotFoundException("Cart items not found in shoppingCart by userId: "
```suggestion
            throw new OrderProcessingException("Cart items not found in shoppingCart by userId: "
```

2024-11-27 15:22 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/service/OrderServiceImpl.java
> +        orderMapper.toDto(savedOrder);
```suggestion
        orderRepository.save(order);
        orderMapper.toDto(order);
```

2024-11-27 15:22 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/service/OrderServiceImpl.java
> +    public void updateOrderStatus(Long orderId, OrderStatusRequestDto requestDto) {
```suggestion
    public UpdateOrderResponseDto updateOrderStatus(Long orderId, OrderStatusRequestDto requestDto) {
```

2024-11-27 15:22 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/service/OrderServiceImpl.java
> +                .map(i -> createOrderItem(order, i))
rename i

2024-11-27 15:22 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/service/OrderServiceImpl.java
> +        order.setOrderDate(LocalDateTime.now());
if you decide to initialise in entity, don't forget to remove here
```
order.setOrderStatus(Order.OrderStatus.PENDING);
order.setOrderDate(LocalDateTime.now());
```

2024-11-27 15:22 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/service/OrderServiceImpl.java
> +    private void cleanShoppingCart(ShoppingCart shoppingCart) {
do you really need this separate method?

2024-11-27 15:22 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/13-create-order-items-table.yaml
> +            tableName: orders_items
```suggestion
            tableName: order_items
```

2024-11-28 11:29 UTC, Sanderfuck approved these changes

2024-11-28 11:37 UTC, merged