Implemented Spring tests
Stelmaschyk/book-store pull request #18
Opened 2024-12-13 15:44 UTC by Stelmaschyk

2024-12-13 20:24 UTC, okuzan requested changes
Good job, some comments

2024-12-13 20:24 UTC, okuzan commented on src/test/java/mate/academy/bookstore/utill/BookProvider.java
> +public class BookProvider {
you can also prevent instantiation of util class

2024-12-13 20:24 UTC, okuzan commented on src/test/java/mate/academy/bookstore/services/CategoryServiceTest.java
> +        verify(bookMapper, times(1)).toBookDto(books.get(1));
times(1) is default, we can omit this

2024-12-13 20:24 UTC, okuzan commented on src/test/java/mate/academy/bookstore/services/CategoryServiceTest.java
> +                .updateCategoryFromDto(updateCategoryRequestDto, category);
repeated twice

2024-12-13 20:24 UTC, okuzan commented on src/test/java/mate/academy/bookstore/services/CategoryServiceTest.java
> +        List<CategoryResponseDto> expectedBookDtos = categories.stream()
misleading name, book vs category

2024-12-13 20:24 UTC, okuzan commented on src/test/java/mate/academy/bookstore/services/CategoryServiceTest.java
> +        assertEquals(expectedMessage, actualMessage);
```suggestion
        String actualMessage = entityNotFoundException.getMessage();

        assertTrue(actualMessage.contains(String.valueOf(TEST_INCORRECT_CATEGORY_ID)));
```
we can make it less dependent on specific wording while still being useful

2024-12-13 20:24 UTC, okuzan commented on src/test/java/mate/academy/bookstore/services/BookServiceTest.java
> +    public void findAllBooks_WithValidCreateBookRequestDto_ShouldReturnListOfBookDto() {
fix name, method doesn't use CreateBookRequestDto

2024-12-13 20:24 UTC, okuzan commented on src/test/java/mate/academy/bookstore/controller/BookControllerTest.java
> +        MvcResult result = mockMvc.perform(delete("/books/{id}", 4)
```suggestion
        mockMvc.perform(delete("/books/{id}", 4)
```

2024-12-13 20:24 UTC, okuzan commented on src/test/java/mate/academy/bookstore/controller/CategoryControllerTest.java
> +                + "/delete-data-from-categories-books-table.sql",
```suggestion
    @Sql(scripts = "classpath:database/categories_books/clear-categories-books-table.sql",
```
let's try to fit it in one line

2024-12-13 20:24 UTC, okuzan commented on src/test/java/mate/academy/bookstore/controller/CategoryControllerTest.java
> +        Assertions.assertEquals(TEST_CATEGORY_AMOUNT, actual.length);
looks a bit complex, will this work?
```suggestion
Page<CategoryResponseDto> page = objectMapper.readValue(
    result.getResponse().getContentAsString(),
    new TypeReference<Page<CategoryResponseDto>>() {}
);
Assertions.assertEquals(TEST_CATEGORY_AMOUNT, page.getContent().size());
```

2024-12-13 20:24 UTC, okuzan commented on pom.xml
> +
```suggestion
```

2024-12-14 13:41 UTC, Stelmaschyk commented on src/test/java/mate/academy/bookstore/services/CategoryServiceTest.java
> +        assertEquals(expectedMessage, actualMessage);
nice idea

2024-12-15 20:12 UTC, sarakhmen requested changes
let's improve your solution :)

2024-12-15 20:12 UTC, sarakhmen commented on src/test/java/mate/academy/bookstore/controller/BookControllerTest.java
> +        EqualsBuilder.reflectionEquals(expected, actual);
I don't see any assertions here

2024-12-15 20:12 UTC, sarakhmen commented on src/test/java/mate/academy/bookstore/controller/BookControllerTest.java
> +        assertThat(bookIds).containsExactlyInAnyOrder(1L, 2L, 3L, 4L);
we can make these 2 assertions in one chain. AssertJ is a powerful library and it provides us such a possibility

2024-12-15 20:12 UTC, sarakhmen commented on src/test/java/mate/academy/bookstore/controller/BookControllerTest.java
> +        Assertions.assertEquals(TEST_ID, actual.getId());
let's use the same assertion library across all tests. I'd recommend using asserJ as previously. Fix in all places

2024-12-16 08:18 UTC, Stelmaschyk commented on src/test/java/mate/academy/bookstore/controller/BookControllerTest.java
> +        assertThat(bookIds).containsExactlyInAnyOrder(1L, 2L, 3L, 4L);
not bad library

2024-12-16 14:03 UTC, Elena-Bruyako approved these changes

2024-12-16 14:33 UTC, merged