Spring Boot JPA task
Stelmaschyk/book-store pull request #2
Opened 2024-08-01 12:50 UTC by Stelmaschyk

2024-08-02 15:38 UTC, MAMentorFX requested changes

2024-08-02 15:38 UTC, MAMentorFX commented on src/main/java/mate/academy/bookstore/repository/BookRepository.java
>      Optional<Book> getBookById(Long id);
Is there a reason to use nativeQuery here? You can do it using default JPA method naming (something like findByIsDeletedIsFalseAndId

2024-08-02 15:38 UTC, MAMentorFX commented on src/main/java/mate/academy/bookstore/service/BookServiceImpl.java
> +            .toList();
Mapstruct supports mapping collections from the box

2024-08-02 15:38 UTC, MAMentorFX commented on src/main/java/mate/academy/bookstore/service/BookServiceImpl.java
> +        existingBook.setCoverImage(updateDto.getCoverImage());
Can it be extracted to bookMapper.updateBook(existingBook, updateDto)

2024-08-04 15:18 UTC, Elena-Bruyako requested changes
see comments

2024-08-04 15:18 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/Book.java
>  @Data
```suggestion
@Getter
@Setter
```

2024-08-04 15:18 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/repository/BookRepository.java
> +    Optional<Book> findByIsDeletedIsFalseAndId(Long id);
```suggestion
```

2024-08-04 15:18 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/service/BookServiceImpl.java
> +        Book book = bookRepository.findByIsDeletedIsFalseAndId(id).orElseThrow(
```suggestion
        Book book = bookRepository.findById(id).orElseThrow(
```

2024-08-04 15:18 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/service/BookServiceImpl.java
> +        Book existingBook = bookRepository.findByIsDeletedIsFalseAndId(id).orElseThrow(
```suggestion
        Book bookd = bookRepository.findById(id).orElseThrow(
```

2024-08-04 15:18 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/service/BookServiceImpl.java
> +        Book updateBook = bookMapper.updateBook(updateDto);
```suggestion
        bookMapper.updateBook(updateDto);
```

2024-08-04 15:18 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/service/BookServiceImpl.java
> +        return bookMapper.toBookDto(bookRepository.save(updateBook));
```suggestion
        return bookMapper.toBookDto(bookRepository.save(book));
```

2024-08-04 15:18 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/mapper/BookMapper.java
> +    Book updateBook(UpdateBookRequestDto updateBook);
```suggestion
    void updateBookFromDto(UpdateBookRequestDto book, @MappingTarget Book entity);
```

2024-08-04 15:18 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/01-create-books-table.yaml
> +            tableName: book
```suggestion
            tableName: books
```

2024-08-04 15:18 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/Book.java
>  @Table(name = "book")
```suggestion
@Table(name = "books")
```

2024-08-04 15:18 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/02-add-is_boolean-column-to-book-table.yaml
> +                  name: is_deleted
replace to 01 changelog, addColumn isn't supported by autorollback

2024-08-05 14:48 UTC, Elena-Bruyako approved these changes

2024-08-05 14:51 UTC, merged