Criteria Query task
Stelmaschyk/book-store pull request #3
Opened 2024-08-09 14:22 UTC by Stelmaschyk

2024-08-11 08:00 UTC, okuzan requested changes

2024-08-11 08:00 UTC, okuzan commented on src/main/java/mate/academy/bookstore/repository/book/spec/TitleSpecificationProvider.java
> +                -> root.get("title").in(Arrays.stream(params).toArray());
extract repeated literal to a constant

2024-08-11 08:00 UTC, okuzan commented on src/main/java/mate/academy/bookstore/repository/book/spec/AuthorSpecificationProvider.java
> +                -> root.get("author").in(Arrays.stream(params).toArray());
same

2024-08-11 08:00 UTC, okuzan commented on src/main/java/mate/academy/bookstore/repository/book/BookSpecificationProviderManager.java
> +                    -> new RuntimeException("No specification provider found for key: " + key));
```suggestion
            .filter(provider -> provider.getKey().equals(key)).findFirst()
            .orElseThrow(()
                    -> new NoSuchElementException("No specification provider found for key: " + key));
```

2024-08-11 08:00 UTC, okuzan commented on src/main/java/mate/academy/bookstore/repository/book/BookSpecificationProviderManager.java
> +
```suggestion
```
don't leave an empty line after method/class definition

2024-08-11 08:00 UTC, okuzan commented on src/main/java/mate/academy/bookstore/repository/book/BookSpecificationBuilder.java
> +
same

2024-09-04 18:21 UTC, sarakhmen approved these changes

2024-09-05 08:53 UTC, merged