GlobalExceptionHandler and isbn validation
Stelmaschyk/book-store pull request #4
Opened 2024-09-05 09:43 UTC by Stelmaschyk

2024-09-05 12:08 UTC, Elena-Bruyako requested changes
see comments

2024-09-05 12:08 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/controller/BookController.java
> +    public BookDto createBook(@RequestBody @Valid CreateBookRequestDto requestDto) {
You can also validate `@PathVariable @Positive Long id` 
add `@Validated` under the controller in such case

2024-09-05 12:08 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/exception/CustomGlobalException.java
> +        return new ResponseEntity<>(body, headers, status);
```suggestion
        return new ResponseEntity<>(body, headers, HttpStatus.BAD_REQUEST);
```

2024-09-05 12:08 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/Book.java
> +    @NotNull
`@Column(nullable = false)` is enough for validation, remove `@NotNull` everywhere

2024-09-05 12:08 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/Book.java
> +    @NotNull
```suggestion
```

2024-09-05 12:08 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/Book.java
> +    @NotNull
```suggestion
    @Column(nullable = false)
```

2024-09-06 17:51 UTC, MentorMateAcademy requested changes

2024-09-06 17:51 UTC, MentorMateAcademy commented on src/main/java/mate/academy/bookstore/exception/CustomGlobalException.java
> +        body.put("errors", errors);
You can save strings to constants

2024-09-06 17:51 UTC, MentorMateAcademy commented on src/main/java/mate/academy/bookstore/exception/CustomGlobalException.java
> +            String field = ((FieldError) e).getField();
```suggestion
        if (e instanceof FieldError fieldError) {
            String field = fieldError.getField();
```

2024-09-06 17:51 UTC, MentorMateAcademy commented on src/main/java/mate/academy/bookstore/model/Book.java
> +    @Min(0)
Use Positive anno

2024-09-08 15:39 UTC, Elena-Bruyako requested changes
see comments

2024-09-08 15:39 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/Book.java
> +    @Positive
```suggestion
```

2024-09-08 15:39 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/Book.java
> +    @Isbn
it should be validated on DTO layer
```suggestion
```

2024-09-08 15:39 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/model/Book.java
>      @Column(nullable = false)
Where is validation on CreateBookRequestDto ?

2024-09-09 12:21 UTC, Elena-Bruyako requested changes
see comments

2024-09-09 12:21 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/controller/BookController.java
> +@Validated
This annotation is needed if you use `@Positive` for `@PathVariable Long id` for example, if not - you can remove it

2024-09-09 12:21 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/dto/CreateBookRequestDto.java
> +    @Positive
```suggestion
    @Positive
    @NotNull
```

2024-09-09 12:21 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/dto/UpdateBookRequestDto.java
> +    @Positive
```suggestion
    @Positive
    @NotNull
```

2024-09-09 12:21 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/dto/UpdateBookRequestDto.java
>      private Long id;
```suggestion
```

2024-09-09 13:07 UTC, Elena-Bruyako approved these changes
well done

2024-09-09 13:14 UTC, merged