Pagination, Sorting, and Swagger task
Stelmaschyk/book-store pull request #5
Opened 2024-09-09 14:03 UTC by Stelmaschyk

2024-09-09 14:15 UTC, Elena-Bruyako requested changes
see comments

2024-09-09 14:15 UTC, Elena-Bruyako commented on pom.xml
> +    <modelVersion>4.0.0</modelVersion>
why there are lots of changes in pom file?

2024-09-09 14:15 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/controller/BookController.java
>      public List<BookDto> searchBook(BookSearchParametersDto searchParameters) {
add Pageable

2024-09-09 16:22 UTC, Stelmaschyk commented on pom.xml
> +    <modelVersion>4.0.0</modelVersion>
Everything is banal, I can’t resolved mergeConflict, having already copied the preparations of the POM.

2024-09-10 06:56 UTC, Elena-Bruyako approved these changes

2024-09-10 18:19 UTC, merged