basic autentication task
Stelmaschyk/book-store pull request #6
Opened 2024-09-16 13:12 UTC by Stelmaschyk

2024-09-16 13:21 UTC, Elena-Bruyako requested changes
see comments

2024-09-16 13:21 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/controller/AuthController.java
> +
```suggestion
```

2024-09-16 13:21 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/dto/book/UpdateBookRequestDto.java
> +    @NotBlank
NotBlank is used for String 
revert to NotNull for BigDecimal

2024-09-16 13:21 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/exception/CustomGlobalException.java
> +        return new ResponseEntity<>(body, headers, status);
```suggestion
        return new ResponseEntity<>(body, headers, HttpStatus.BAD_REQUEST);
```

2024-09-16 13:21 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/service/UserServiceImpl.java
> +        if (userRepository.findByEmail(requestDto.getEmail()).isPresent()) {
```suggestion
        if (userRepository.existsByEmail(requestDto.getEmail())) {
```

2024-09-16 13:21 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/service/UserServiceImpl.java
> +        user.setEmail(requestDto.getEmail());
use MapStruct for this purpose

2024-09-16 13:21 UTC, Elena-Bruyako commented on src/main/java/mate/academy/bookstore/service/UserServiceImpl.java
> +        return userMapper.toUserDto(savedUser);
```suggestion
        userRepository.save(user);
        return userMapper.toUserDto(user);
```

2024-09-17 07:05 UTC, liliia-ponomarenko approved these changes
Awesome 😎

2024-09-17 07:05 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/02-create-users-table.yaml
> +                    nullable: false
```suggestion
                    nullable: false
                    
```
Leave one empty line at the end of the file ;)

2024-09-17 07:05 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +      file: /db/changelog/changes/02-create-users-table.yaml
the same

2024-09-17 07:06 UTC, liliia-ponomarenko approved these changes

2024-09-25 18:23 UTC, ahoienko approved these changes
Good job!

2024-09-26 05:20 UTC, merged