implemeted JWT functionality
Stelmaschyk/book-store pull request #7
Opened 2024-09-30 10:07 UTC by Stelmaschyk

2024-10-01 08:15 UTC, liliia-ponomarenko approved these changes
LGTM 🔥

2024-10-01 08:15 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/bookstore/security/JwtAuthenticationFilter.java
> +    private static final String TYPE_OF_HEADER = "Authorization";
You can use HttpHeader.AUTHORIZATION instead of your constant ;)

2024-10-01 08:15 UTC, liliia-ponomarenko commented on src/main/resources/application.properties
> +jwt.secret=AbstractAutowireCapableBeanFactory.createBeanInstance
better generate some random symbols ;)

2024-10-16 13:08 UTC, Elena-Bruyako requested changes
Changes were approved two weeks ago (actually it was JWT HW implementation). Please provide new PR with Category HW implementation

2024-10-16 13:08 UTC, Elena-Bruyako commented
<img width="946" alt="Screenshot 2024-10-16 at 16 05 22" src="https://github.com/user-attachments/assets/d1a595a2-2e45-48f0-b0a8-b27b474313c6">

2024-10-16 13:51 UTC, closed without merging